service: wellness-companion

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    JWT_SECRET: ${env:JWT_SECRET, 'dev-secret-change-in-prod'}
    USERS_TABLE: ${self:service}-users-${self:provider.stage}
    TRACKING_TABLE: ${self:service}-tracking-${self:provider.stage}
    REMINDERS_TABLE: ${self:service}-reminders-${self:provider.stage}
    JOURNAL_ENTRIES_TABLE: ${self:service}-journal-entries-${self:provider.stage}
    USER_CONTEXT_TABLE: ${self:service}-user-context-${self:provider.stage}
    INSIGHT_QUEUE_TABLE: ${self:service}-insight-queue-${self:provider.stage}
    PHOTOS_BUCKET: ${self:service}-photos-${self:provider.stage}
    COGNITO_USER_POOL_ID: us-east-1_fTxU26uy4
    COGNITO_CLIENT_ID: 3i8iauebg4sseeh6qdlstncmh9
    VAPID_PUBLIC_KEY: ${env:VAPID_PUBLIC_KEY, 'BP83nSNqLs_KnH2iFtIvJqAIMVMQtFFlTevsgz5o1nzZHhfozU9YGXwNkpSGnIB6e_4FEnXTX9x8jxS5YcI4lqA'}
    VAPID_PRIVATE_KEY: ${env:VAPID_PRIVATE_KEY, '1-Rbe8xi9Ufmoq0CxIhJpLrl5DJustXlfbO8_2FwJW8'}
    VAPID_EMAIL: ${env:VAPID_EMAIL, 'mailto:admin@wellness-companion.com'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.USERS_TABLE}
            - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.TRACKING_TABLE}
            - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.REMINDERS_TABLE}
            - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.JOURNAL_ENTRIES_TABLE}
            - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.USER_CONTEXT_TABLE}
            - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.INSIGHT_QUEUE_TABLE}
            - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.USERS_TABLE}/index/*
            - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.TRACKING_TABLE}/index/*
            - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.INSIGHT_QUEUE_TABLE}/index/*
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::${self:provider.environment.PHOTOS_BUCKET}/*
        - Effect: Allow
          Action:
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminGetUser
            - cognito-idp:AdminUpdateUserAttributes
          Resource:
            - arn:aws:cognito-idp:${aws:region}:*:userpool/*
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: '*'
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - arn:aws:lambda:${aws:region}:*:function:${self:service}-${self:provider.stage}-notificationHandler
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource:
            - arn:aws:bedrock:${aws:region}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0
            - arn:aws:bedrock:${aws:region}::foundation-model/amazon.titan-embed-text-v1

plugins:
  - serverless-plugin-typescript

functions:
  # Auth endpoints
  register:
    handler: functions/auth/register.handler
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  login:
    handler: functions/auth/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  profile:
    handler: functions/auth/profile.handler
    events:
      - http:
          path: user/profile
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  # Tracking endpoints
  checkin:
    handler: functions/tracking/checkin.handler
    events:
      - http:
          path: tracking/checkin
          method: post
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer:
            name: authorizerFunc
            type: request

  photo:
    handler: functions/tracking/photo.handler
    events:
      - http:
          path: tracking/photo
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  weight:
    handler: functions/tracking/weight.handler
    events:
      - http:
          path: tracking/weight
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  supplement:
    handler: functions/tracking/supplement.handler
    events:
      - http:
          path: tracking/supplement
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  history:
    handler: functions/tracking/history.handler
    events:
      - http:
          path: tracking/history
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  # Notification Functions
  notificationSubscribe:
    handler: functions/notifications/subscribe.handler
    events:
      - http:
          path: notifications/subscribe
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  notificationHandler:
    handler: functions/notifications/handler.handler
    environment:
      NOTIFICATION_HANDLER_FUNCTION: ${self:service}-${self:provider.stage}-notificationHandler
    events:
      - http:
          path: notifications/send
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  scheduledNotificationTrigger:
    handler: functions/notifications/enhanced-trigger.handler
    environment:
      NOTIFICATION_HANDLER_FUNCTION: ${self:service}-${self:provider.stage}-intelligentNotificationSender
    events:
      - schedule: 
          rate: cron(0 7 * * ? *)  # 7 AM UTC daily
          input:
            detail-type: morning
      - schedule:
          rate: cron(0 12 * * ? *)  # 12 PM UTC daily
          input:
            detail-type: lunch
      - schedule:
          rate: cron(0 18 * * ? *)  # 6 PM UTC daily
          input:
            detail-type: supplement
      - schedule:
          rate: cron(0 21 * * ? *)  # 9 PM UTC daily
          input:
            detail-type: evening
  
  intelligentNotificationSender:
    handler: functions/notifications/intelligent-sender.sendIntelligentNotification
    events:
      - http:
          path: notifications/send-intelligent
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  # Journal endpoints
  journalCreate:
    handler: functions/journal/handler.createEntry
    events:
      - http:
          path: journal/entry
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  journalList:
    handler: functions/journal/handler.getEntries
    events:
      - http:
          path: journal/entries
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  journalGet:
    handler: functions/journal/handler.getEntry
    events:
      - http:
          path: journal/entry/{entryId}
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  journalUpdate:
    handler: functions/journal/handler.updateEntry
    events:
      - http:
          path: journal/entry/{entryId}
          method: put
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  journalDelete:
    handler: functions/journal/handler.deleteEntry
    events:
      - http:
          path: journal/entry/{entryId}
          method: delete
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  journalProcess:
    handler: functions/journal/process-entry.handler
    timeout: 30
    events:
      - http:
          path: journal/process
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  journalSearch:
    handler: functions/journal/search.handler
    timeout: 30
    events:
      - http:
          path: journal/search
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  journalContext:
    handler: functions/journal/context.handler
    events:
      - http:
          path: journal/context
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            type: request

  # Authorizer
  authorizerFunc:
    handler: functions/auth/authorizer.handler

resources:
  Resources:
    # Gateway Responses for CORS
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
    
    GatewayResponseDefault5XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: ApiGatewayRestApi
    
    # DynamoDB Tables
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    TrackingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TRACKING_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    RemindersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.REMINDERS_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: reminderId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: reminderId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    # Journal Entries Table
    JournalEntriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.JOURNAL_ENTRIES_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: entryId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: entryId
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        BillingMode: PAY_PER_REQUEST

    # User Context Table
    UserContextTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_CONTEXT_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: contextType
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: contextType
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    # Insight Queue Table
    InsightQueueTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.INSIGHT_QUEUE_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: taskId
            AttributeType: S
          - AttributeName: scheduledFor
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: taskId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: scheduledFor-index
            KeySchema:
              - AttributeName: scheduledFor
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    # S3 Bucket for photos
    PhotosBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.PHOTOS_BUCKET}-${aws:accountId}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
              MaxAge: 3000
        LifecycleConfiguration:
          Rules:
            - Id: DeleteOldPhotos
              Status: Enabled
              ExpirationInDays: 90